import type { ScreenerConfig } from "./types"

export const ASRS: ScreenerConfig = {
    id: "asrs-v1.1",
    category: "adhd",
    slug: "adhd/asrs",
    name: "ASRS-v1.1",
    fullName: "Adult ADHD Self-Report Scale (ASRS-v1.1) Screener",
    description: "A 6-question screening tool developed by the World Health Organization to help identify adults who may have ADHD.",
    purpose: "This screener asks about symptoms of ADHD in adults. A positive result suggests you may benefit from a comprehensive ADHD evaluation by a qualified provider.",
    timeEstimate: "2 minutes",
    questionCount: 6,
    citation: "Developed by the World Health Organization (WHO) in conjunction with Drs. Lenard Adler, Ronald Kessler, and Thomas Spencer. Free for clinical and research use.",
    citationUrl: "https://www.hcp.med.harvard.edu/ncs/asrs.php",
    disclaimer: "This screening tool is not a diagnostic instrument. ADHD can only be diagnosed by a qualified healthcare provider through a comprehensive evaluation including history, symptoms, and ruling out other conditions.",
    standardOptions: [
        { value: 0, label: "Never" },
        { value: 1, label: "Rarely" },
        { value: 2, label: "Sometimes" },
        { value: 3, label: "Often" },
        { value: 4, label: "Very Often" },
    ],
    questions: [
        {
            id: 1,
            question: "How often do you have trouble wrapping up the final details of a project, once the challenging parts have been done?",
            options: [
                { value: 0, label: "Never" },
                { value: 0, label: "Rarely" },
                { value: 0, label: "Sometimes" },
                { value: 1, label: "Often" },
                { value: 1, label: "Very Often" },
            ],
        },
        {
            id: 2,
            question: "How often do you have difficulty getting things in order when you have to do a task that requires organization?",
            options: [
                { value: 0, label: "Never" },
                { value: 0, label: "Rarely" },
                { value: 0, label: "Sometimes" },
                { value: 1, label: "Often" },
                { value: 1, label: "Very Often" },
            ],
        },
        {
            id: 3,
            question: "How often do you have problems remembering appointments or obligations?",
            options: [
                { value: 0, label: "Never" },
                { value: 0, label: "Rarely" },
                { value: 0, label: "Sometimes" },
                { value: 1, label: "Often" },
                { value: 1, label: "Very Often" },
            ],
        },
        {
            id: 4,
            question: "When you have a task that requires a lot of thought, how often do you avoid or delay getting started?",
            options: [
                { value: 0, label: "Never" },
                { value: 0, label: "Rarely" },
                { value: 0, label: "Sometimes" },
                { value: 0, label: "Often" },
                { value: 1, label: "Very Often" },
            ],
        },
        {
            id: 5,
            question: "How often do you fidget or squirm with your hands or feet when you have to sit down for a long time?",
            options: [
                { value: 0, label: "Never" },
                { value: 0, label: "Rarely" },
                { value: 0, label: "Sometimes" },
                { value: 0, label: "Often" },
                { value: 1, label: "Very Often" },
            ],
        },
        {
            id: 6,
            question: "How often do you feel overly active and compelled to do things, like you were driven by a motor?",
            options: [
                { value: 0, label: "Never" },
                { value: 0, label: "Rarely" },
                { value: 0, label: "Sometimes" },
                { value: 1, label: "Often" },
                { value: 1, label: "Very Often" },
            ],
        },
    ],
    scoring: {
        min: 0,
        max: 6,
        thresholds: [
            { min: 0, max: 3, level: "negative" },
            { min: 4, max: 6, level: "positive" },
        ],
    },
    resultLevels: {
        negative: {
            level: "negative",
            title: "Negative Screen for Adult ADHD",
            description: "Based on your responses, you do not currently meet the screening threshold for adult ADHD. However, if you are experiencing difficulties with attention, organization, or impulsivity that affect your life, you may still benefit from an evaluation.",
            color: "text-green-700",
            bgColor: "bg-green-50 border-green-200",
            iconColor: "bg-green-100",
            recommendations: [
                "If attention or focus issues are affecting your work or relationships, consider speaking with a provider",
                "Many strategies for organization and productivity can help anyone",
                "Other conditions like anxiety, depression, or sleep disorders can cause similar symptoms",
                "Consider whether stress or life circumstances might be affecting your concentration",
                "Maintain good sleep hygiene and regular routines",
            ],
            resources: [
                { title: "Self-Care Toolkit", href: "/resources/self-care", description: "Tips for focus and productivity" },
                { title: "About ADHD", href: "/conditions/adhd", description: "Learn more about ADHD symptoms" },
                { title: "Schedule a Consultation", href: "/contact", description: "Discuss your concerns with a provider" },
            ],
        },
        positive: {
            level: "positive",
            title: "Positive Screen for Adult ADHD",
            description: "Your responses suggest symptoms consistent with adult ADHD. A positive screen does not mean you have ADHD, but it indicates that a comprehensive evaluation by a qualified provider would be beneficial.",
            color: "text-orange-700",
            bgColor: "bg-orange-50 border-orange-200",
            iconColor: "bg-orange-100",
            recommendations: [
                "Schedule an appointment for a comprehensive ADHD evaluation",
                "A full evaluation includes history, symptom assessment, and ruling out other conditions",
                "ADHD is highly treatable with medication and/or behavioral strategies",
                "Many successful adults have ADHD and manage it effectively",
                "Bring examples of how symptoms affect your daily life to your appointment",
                "Consider asking family members about your childhood behaviors",
            ],
            resources: [
                { title: "Schedule an Evaluation", href: "/contact", description: "Get a comprehensive ADHD assessment" },
                { title: "About ADHD", href: "/conditions/adhd", description: "Learn about ADHD in adults" },
                { title: "ADHD Treatment Services", href: "/services/adhd-treatment", description: "Our specialized ADHD care" },
                { title: "Pharmacogenomic Testing", href: "/services/pharmacogenomic-testing", description: "Optimize medication selection" },
            ],
        },
    },
    relatedCondition: "adhd",
    relatedAssessments: ["phq-9", "gad-7"],
}