import type { ScreenerConfig } from "./types";

export const PHQ9: ScreenerConfig = {
    id: "phq-9",
    category: "depression",
    slug: "depression/phq-9",
    name: "PHQ-9",
    fullName: "Patient Health Questionnaire-9",
    description: "A validated 9-question screening tool used to assess the severity of depression symptoms over the past two weeks.",
    purpose: "This screener helps identify depression symptoms and their impact on daily functioning. It is widely used in clinical settings to monitor depression severity and treatment response.",
    timeEstimate: "2-3 minutes",
    questionCount: 9,
    citation: "Developed by Drs. Robert L. Spitzer, Janet B.W. Williams, Kurt Kroenke and colleagues. Public domain.",
    citationUrl: "https://www.phqscreeners.com/",
    disclaimer: "This screening tool is not a diagnostic instrument. A diagnosis of depression can only be made by a qualified healthcare provider through a comprehensive evaluation.",
    standardOptions: [
        { value: 0, label: "Not at all" },
        { value: 1, label: "Several days" },
        { value: 2, label: "More than half the days" },
        { value: 3, label: "Nearly every day" },
    ],
    questions: [
        {
            id: 1,
            question: "Little interest or pleasure in doing things",
        },
        {
            id: 2,
            question: "Feeling down, depressed, or hopeless",
        },
        {
            id: 3,
            question: "Trouble falling or staying asleep, or sleeping too much",
        },
        {
            id: 4,
            question: "Feeling tired or having little energy",
        },
        {
            id: 5,
            question: "Poor appetite or overeating",
        },
        {
            id: 6,
            question: "Feeling bad about yourself - or that you are a failure or have let yourself or your family down",
        },
        {
            id: 7,
            question: "Trouble concentrating on things, such as reading the newspaper or watching television",
        },
        {
            id: 8,
            question: "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual",
        },
        {
            id: 9,
            question: "Thoughts that you would be better off dead, or of hurting yourself in some way",
            isCritical: true,
            criticalThreshold: 1,
        },
    ],
    scoring: {
        min: 0,
        max: 27,
        thresholds: [
            { min: 0, max: 4, level: "minimal" },
            { min: 5, max: 9, level: "mild" },
            { min: 10, max: 14, level: "moderate" },
            { min: 15, max: 19, level: "moderatelySevere" },
            { min: 20, max: 27, level: "severe" },
        ],
    },
    criticalQuestionId: 9,
    criticalThreshold: 1,
    resultLevels: {
        minimal: {
            level: "minimal",
            title: "Minimal Depression",
            description: "Your responses suggest minimal or no depression symptoms. While everyone experiences low moods occasionally, your current symptoms are within the normal range.",
            color: "text-green-700",
            bgColor: "bg-green-50 border-green-200",
            iconColor: "bg-green-100",
            recommendations: [
                "Continue maintaining healthy lifestyle habits",
                "Practice regular self-care and stress management",
                "Stay connected with supportive relationships",
                "Monitor your mood and seek help if symptoms increase",
                "Consider preventive measures like regular exercise and good sleep hygiene",
            ],
            resources: [
                { title: "Self-Care Toolkit", href: "/resources/self-care", description: "Tools for maintaining mental wellness" },
                { title: "Wellness Resources", href: "/resources", description: "Explore our full resource library" },
            ],
        },
        mild: {
            level: "mild",
            title: "Mild Depression",
            description: "Your responses suggest mild depression symptoms. While not severe, these symptoms may be affecting your quality of life and could benefit from attention.",
            color: "text-yellow-700",
            bgColor: "bg-yellow-50 border-yellow-200",
            iconColor: "bg-yellow-100",
            recommendations: [
                "Consider speaking with a healthcare provider about your symptoms",
                "Implement regular exercise (shown to improve mild depression)",
                "Practice good sleep hygiene and maintain consistent routines",
                "Engage in activities you typically enjoy, even when you don't feel like it",
                "Connect with friends and family for social support",
                "Monitor your symptoms and seek help if they worsen",
            ],
            resources: [
                { title: "Self-Care Toolkit", href: "/resources/self-care", description: "Evidence-based wellness strategies" },
                { title: "Support Groups", href: "/resources/support-groups", description: "Connect with others who understand" },
                { title: "Schedule a Consultation", href: "/contact", description: "Speak with one of our providers" },
            ],
        },
        moderate: {
            level: "moderate",
            title: "Moderate Depression",
            description: "Your responses indicate moderate depression symptoms. At this level, symptoms are likely affecting your daily functioning and professional evaluation is recommended.",
            color: "text-orange-700",
            bgColor: "bg-orange-50 border-orange-200",
            iconColor: "bg-orange-100",
            recommendations: [
                "Schedule an appointment with a mental health provider",
                "Consider both therapy and medication options",
                "Don't try to manage this alone - reach out for professional support",
                "Maintain basic self-care routines even when difficult",
                "Limit alcohol and avoid recreational drugs",
                "Tell a trusted person how you're feeling",
            ],
            resources: [
                { title: "Schedule an Appointment", href: "/contact", description: "Connect with our care team" },
                { title: "Meet Our Providers", href: "/providers", description: "Find a provider who can help" },
                { title: "About Mood Disorders", href: "/conditions/mood", description: "Learn about treatment options" },
            ],
        },
        moderatelySevere: {
            level: "moderatelySevere",
            title: "Moderately Severe Depression",
            description: "Your responses suggest moderately severe depression. This level of symptoms significantly impacts daily life and requires professional treatment. Please reach out for help.",
            color: "text-orange-700",
            bgColor: "bg-orange-50 border-orange-200",
            iconColor: "bg-orange-100",
            recommendations: [
                "Seek professional help as soon as possible",
                "Treatment combining therapy and medication is often most effective at this level",
                "Share your results with a healthcare provider",
                "If you're having thoughts of self-harm, please reach out immediately",
                "Ask someone you trust to help you access care",
                "Remember: depression is treatable and you can feel better",
            ],
            resources: [
                { title: "Schedule Now", href: "/contact", description: "Book an appointment with our team" },
                { title: "Crisis Resources", href: "/resources/crisis", description: "Immediate support available 24/7" },
                { title: "Our Services", href: "/services", description: "Learn about our treatment approach" },
            ],
        },
        severe: {
            level: "severe",
            title: "Severe Depression",
            description: "Your responses indicate severe depression symptoms. This requires immediate professional attention. Effective treatments are available, and with proper care, most people experience significant improvement.",
            color: "text-red-700",
            bgColor: "bg-red-50 border-red-200",
            iconColor: "bg-red-100",
            recommendations: [
                "Contact a mental health provider or your primary care doctor today",
                "If you're having thoughts of suicide, call 988 immediately",
                "Do not try to manage severe depression on your own",
                "Consider intensive treatment options if available",
                "Have someone stay with you if you're in crisis",
                "Remember: severe depression is treatable - please reach out for help",
            ],
            resources: [
                { title: "Call 988", href: "tel:988", description: "Suicide & Crisis Lifeline - Available 24/7" },
                { title: "Contact Us Now", href: "/contact", description: "Our team can help you access urgent care" },
                { title: "Crisis Resources", href: "/resources/crisis", description: "Emergency support and hotlines" },
            ],
        },
    },
    relatedCondition: "mood",
    relatedAssessments: ["gad-7", "phq-2"],
}